name: nlp-t2
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  # Core
  - python=3.11

  # PyTorch con CUDA
  - pytorch
  - pytorch-cuda=12.1

  # Utilidades del sistema
  - pip

  # Paquetes vía pip
  - pip:
      # NLP / HF stack
      - transformers
      - datasets
      - accelerate
      - peft
      - safetensors
      - sentencepiece
      - protobuf
      - pyarrow

      # QLoRA / 4-bit
      - bitsandbytes>=0.43

      # Data pipeline
      - pandas
      - langdetect
      - lyricsgenius
      - unidecode
      - scikit-learn

      # Otros
  - numpy
  - matplotlib
  - seaborn

